config/routes.rb
Rails.application.routes.draw do
  resources :comment,only: [:index, :create,:new,:show]
  #resources :tangbt
  # root 'comment#home'
  root 'welcome#index'

  resources :home, only: [:index, :create] do
  	collection do
  		get 'upfiles'
  	end
  end

  resources :mark, :share, :knowledge, :book, :life, :about, :welcome do
    
  end

  # system background
  namespace :admin do
    root 'login#index'

    resources :login, only: [:index, :new] do

    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :title, presence: true
  #self.create(title: "John Doe").valid? # => true
 # self.create(content: nil).valid? # => false

   #def new 
    #@result = Comments.new
  #end
  class << self   
    def save params
       #print '23'
       #self.new params
      # validates :titlte, presence: true
       #self.create(title: "John Doe").valid? # => true
       #self.create(content: nil).valid? # => false
       @result = self.create params
       #@resutl = saveinfo params
    end

     # get all information
    def getall
      @result = self.all
    end

    # get comment info by id
    def detail params
        self.find(params)
    end
    
    # present not use
    def saveinfo params
      @result = Comment.save(params)
    end
  end
end

app/controllers/comment_controller.rb
# encoding: utf-8
class CommentController < ApplicationController
  
  # home page 
  def index
    @comment = Comment.new
    render layout: false
  end
  # create page
  def create
    #debugger
    print "author: tangbt testinfo/r/n"
    @comment = Comment.save getcreate
    #render  'comment/index'
    redirect_to '/comment'
    #render 'comment/list'
  end
 
# del page
  def  del
  	
  end

   # show a product
   def show
      @getinfo = Digest::MD5.hexdigest(BaseConfig.getip) 
      
      # send email
      @commentdetail = Comment.detail params[:id]
   end

   # home page
  def home
    @comment_all = Comment.getall
    render 'comment/list'
  end

  # new page
  def  new

  end
  # edit page
  def edit

  end

  # update page
  def update 

  end 

  private 
    def  getcreate
      @post = Post.find(params[:title])
      @comment = @post.comments.new(params[:comment])
      BaseConfig.sendmail
      params.require(:comment).permit(:title, :content)
    end
 
end

app/views/comment/_form_comment.html.erb
 <%= form_for @comment , url: comment_index_path, remote: true do |f| %>
      <%= link_to "主题" %>
      <%= f.text_field :title, class: "textobx", id: "title" %>
      <br/>
      <%= link_to "内容" %>
      <%= f.text_field :content,class: "textbox",id: "content" %>
      <br/>
      <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %> 
      <%= f.submit %>
    <% end %>

app/views/comment/get_content.html.erb
<html>
<head>
<title>
</title>
</head>
<body>
1111111111111111
</body>
</html>

app/views/comment/index.html.erb
<html>
  <head>
    <title>
	title
    </title>
  </head>
  <body>
    <div>
      hello ruby
    </div>
   <%= render "comment/form_comment" %>
  </body>
</html>

app/views/comment/list.html.erb
<html>
  <head>
    <title>
       comment list
    </title>
  </head>
  <body>
    <div>
      <span style='font-size:14px;font-weight:bold;line-height:30px;'>
         List
	<a href='/get_content' >get_content</a>
      </span>
      <br/>
      <ul  style="list-style:none;">
        <li  style='line-height:30px;font-size:15px;'>
           <div style='width:20%;float:left;'>
            Id
           </div>
          <div style='width:40%;float:left;'>
            标题
          </div>
           <div style='width:40%;float:left;'>
            内容
          </div>
        </li>
       <% @comment_all.each do |f|%>
        <li  style='line-height:30px;font-size:15px;'>
          <div style='width:20%;float:left;'>
            <%= link_to f.id ,f , alt:f.id %>
          </div>
          <div style='width:40%;float:left;'>
            <%= link_to f.title ,f , alt:f.title %>
          </div>
          <div style='width:40%;float:left;'>
            <%= link_to f.content%>
          </div>
          </li>
          <br/>
       <% end %>
        </ul>
    </div>
  </body>
</html>

app/views/comment/show.html.erb
<html>
  <head>
    <title>
      Detail info
    </title>
  </head>
  <body>
    <div>
    <a href= "/">
      <input type='button'  value='Home' />
    </a>
    <a href="javascript:window.history.go(-1)">
      <input type='button'  value='Preview' />
    </a>
    <a href="/comment">
      <input type='button'  value='Add' />
    </a>
    <br/>
      <span style="font-size:30px;font-weight:bold;">
        Comment Detail Info
        <br/>
         标题:<%= raw @commentdetail.title %>
         <br/>
         内容:<%= raw @commentdetail.content %>
         <br/>
        配置:<%= raw @getinfo %> 
      </span>
    </div>
  </body>
</html>